### ISSUE TITLE
Update Section 4.9.7 before October

### ISSUE THREAD

**Issue by aarongable** [letsencrypt/cp-cps#168]
[It says](https://github.com/letsencrypt/cp-cps/blob/main/CPS.md#498-maximum-latency-for-crls-if-applicable)

> ISRG does not issue CRLs for Subscriber Certificates.

This will no longer be true once we start issuing CRLs to comply with Apple and Mozilla's upcoming root program requirements.

**Comment by jprenken** [comment]
Fixed by #172
