### ISSUE TITLE
Certificate expiration notice

### ISSUE THREAD

**Issue by tdelmas** [letsencrypt/cp-cps#17]
https://github.com/letsencrypt/cp-cps/blob/master/CPS.md#411-end-of-subscription

> A Subscriber's subscription ends once all of Subscriber's ISRG certificates have expired or been revoked.

> Prior to the end of subscription, ISRG will send the Subscriber notice of pending Certificate expiration, in the form of a renewal notification, when 20% of the certificate’s lifetime remains, if a contact email address was provided.

The "renewal notification" is not sent "prior to the end of subscription" but "prior to a certificate expiration", right? And only if the Subscriber did not opt-out (via the unsubscribe link)

I propose the following wording instead:

> Prior to a Subscriber's certificate expiration, ISRG will send the Subscriber notice of pending Certificate expiration, in the form of a renewal notification, when 20% of the certificate’s lifetime remains, if a contact email address was provided and the Subscriber did not opt-ou for these notifications.

**Comment by bdaehlie** [comment]
Thanks for pointing this out. I addressed this issue in this commit:

https://github.com/letsencrypt/cp-cps/commit/dc272814b2e516a4c79b6ef2394d86a60c9aa77f
