### ISSUE TITLE
Review CP/CPS for "No stipulation"

### ISSUE THREAD

**Issue by jsha** [letsencrypt/cp-cps#19]
Per https://wiki.mozilla.org/CA/Required_or_Recommended_Practices#CP.2FCPS_Structured_According_to_RFC_3647, Mozilla may forbid the use of "No stipulation" soon in preference for more informative statements like "The section does not apply," or "The CA does not do X." We should review our CP/CPS to bring it into line with that guidance.

**Comment by bdaehlie** [comment]
Here is a link to the discussion:

https://groups.google.com/forum/#!topic/mozilla.dev.security.policy/Cth8n4mxxmQ

**Comment by bdaehlie** [comment]
This has been done.
