### ISSUE TITLE
Sections mentioning RA can be simplified

### ISSUE THREAD

**Issue by jsha** [letsencrypt/cp-cps#2]
Early on, we say:

> ISRG serves as its own RA. RA services are not performed by third parties.

But later:

> 9.6.2 RA representations and warranties
> Each RA represents and warrants that:
> The RA’s certificate issuance and management services conform to the ISRG CP and this CPS,
Information provided by the RA does not contain any false or misleading information,
Translations performed by the RA are an accurate translation of the original information, and
All certificates requested by the RA meet the requirements of this CPS.
ISRG’s agreement with the RA may contain additional representations and warranties.

> 9.16.1 Entire agreement
> ISRG contractually obligates each RA to comply with this CPS and applicable industry guidelines. ISRG also requires each party using its products and services to enter into an agreement that delineates the terms associated with the product or service. If an agreement has provisions that differ from this CPS, then the agreement with that party controls, but solely with respect to that party. Third parties may not rely on or bring action to enforce such agreement.

These can probably be simplified to say "ISRG does not use RA services from third parties."

**Comment by bdaehlie** [comment]
Fixed in commit 6380ef8
