### ISSUE TITLE
Clarify manual validation statement in CPS

### ISSUE THREAD

**Issue by pgporada** [letsencrypt/cp-cps#20]
The following statement is true during some revocation events. I don't believe there's ever been an occurrence during an issuance where this has happened.

https://github.com/letsencrypt/cp-cps/blame/master/CPS.md#L269
```In exceptional cases control may be validated using methods similar to those employed by ACME, but performed manually.```

**Comment by bdaehlie** [comment]
Fixed in commit a6bac4b
