### ISSUE TITLE
Consider moving 6.1.5 Key Sizes directly into 7.1 Certificate Profiles as "Subject Public Key"

### ISSUE THREAD

**Issue by pgporada** [letsencrypt/cp-cps#213]
The key types and key sizes seem in [section 6.1.5](https://letsencrypt.org/documents/isrg-cp-cps-v5.2/#6.1.5-key-sizes) seem, to me, to be better suited in [section 7.1](https://letsencrypt.org/documents/isrg-cp-cps-v5.2/#7.1-certificate-profile) certificate profile in the subject public key field.

**Comment by aarongable** [comment]
Should be the Subject Public Key field, not the signature field.
