### ISSUE TITLE
Remove all-caps from CPS Secs. 9.7 & 9.8

### ISSUE THREAD

**Issue by jprenken** [letsencrypt/cp-cps#22]
The text of CPS sections 9.7 ("Disclaimers of warranties") and 9.8 ("Limitations of liability") is in all capital letters. This is an anti-pattern. See, e.g.: https://typographyforlawyers.com/all-caps.html

> One of the most tenacious urban legends in legal typography is the belief in the infallibility of caps in contracts. ...
> 
> Some lawyers have nevertheless insisted that caps reliably satisfy laws requiring "conspicuous" text, many of which are derived from the Uniform Commercial Code. Oh really? The UCC defines "conspicuous" as "presented [so] that a reasonable person ... ought to have noticed it," and noting that "[w]hether a term is 'conspicuous' or not is a decision for the court." UCC § 1-201(b)(10). On that point, the Ninth Circuit has held that "[l]awyers who think their caps lock keys are instant 'make conspicuous' buttons are deluded." _In re Bassett_, 285 F.3d 882, 886 (9th Cir. 2002). I concur.

Butterick, M. (2015). Typography for lawyers (2nd ed.). Houston, TX: Jones McClure.

**Comment by bdaehlie** [comment]
Fixed

**Comment by jprenken** [comment]
Thanks! This also applies to the Subscriber Agreement's section 4.4.
