### ISSUE TITLE
Add missing tags

### ISSUE THREAD

**Issue by tdelmas** [letsencrypt/cp-cps#24]
git tag CP-v2.0 2a249d316b1173db72612f5f0e6e279589aae78f
git tag CP-v2.1 a3f880ca179c42c44940117d54caf949a11f0151
git tag CP-v2.2 4ba8d69719b93b1ce6a564fa0bacc6a41093e17e
git tag CP-v2.3 7754a5382e19c380ebc30a9a4990deee9703daec
git tag CP-v2.4 0c150a8499ea7871ad24e5ffda6e19a5a94dac1d

git tag CPS-v2.1 a3f880ca179c42c44940117d54caf949a11f0151
git tag CPS-v2.2 7f3b765eb4f68a1b36609c2d817b227d39995fcb
git tag CPS-v2.3 f2093388381f6d246aad99e4368915e3b6134657
git tag CPS-v2.4 4ba8d69719b93b1ce6a564fa0bacc6a41093e17e
git tag CPS-v2.5 d3f20b50ae52bebb87eae4ae0123fa2f79146662
git tag CPS-v2.6 7754a5382e19c380ebc30a9a4990deee9703daec
git tag CPS-v2.7 39b94a6f59049b566b0a85d8222a46b512efa5c4

(I checked for each ref it was indeed the version published on https://letsencrypt.org/repository/ with a text-diff)

nb: the tag `CPS-v2.0` already exists

**Comment by bdaehlie** [comment]
What would I need to do here? Just run those commands?

**Comment by tdelmas** [comment]
Yes, and push them after:
`git push --tags --dry-run` and if the list is correct, `git push --tags`

**Comment by bdaehlie** [comment]
Done, thanks!
