### ISSUE TITLE
Change OCSP requirements 4.9.10

### ISSUE THREAD

**Issue by andygabby** [letsencrypt/cp-cps#29]
Changes to the BRs no longer require a root ocsp responder indicating the status of a subordinate ca (as long as an ocsp responder is not embedded into the certificate). We should change the wording to be in line with the new BR requirements which is applicable to the new subordinate certificates.

**Comment by bdaehlie** [comment]
I believe the change making it so we don't need OCSP in subordinate certificates is actually to Section 7.1.2.2 "Subordinate CA certificate."

**Comment by bdaehlie** [comment]
Should be resolved in commit 53bae50.
