### ISSUE TITLE
Update 4.9.12 to enumerate methods to demonstrate key compromise

### ISSUE THREAD

**Issue by aarongable** [letsencrypt/cp-cps#39]
As per a new addition in version 2.7.1 of Mozilla's root program requirements, effective May 1, 2021:

> Section 4.9.12 of a CA's CP/CPS MUST clearly specify the methods that parties may use to demonstrate private key compromise.

https://github.com/mozilla/pkipolicy/blob/1829373903c8d58246c781ee11ea77d6d386985a/rootstore/policy.md#L708-709

As of today, Section 4.9.12 of our CP says simply "See Section 4.9.1", which only lists the _reasons_ for revocation, not the mechanisms by which key compromise may be demonstrated. Section 4.9.12 of our CPS says "No stipulation".

**Comment by jprenken** [comment]
It looks like this was fixed by #43 , correct?

**Comment by aarongable** [comment]
I believe so, yes.
