### ISSUE TITLE
Update CP section 7.1.4.2.2 specifically for our DV certs

### ISSUE THREAD

**Issue by pgporada** [letsencrypt/cp-cps#50]
https://bugzilla.mozilla.org/show_bug.cgi?id=1701317#c6

This portion has been addressed in a prior commit.
> Section 3.1.1 of the CPS says, “Certificate distinguished names and subject alternative names are compliant with the CP.” Section 7.1.4 of the CPS also refers to the CP. Section 7.1.4.2.1 of the CP (Subject alternative name extension) contains unnecessary language copied from the Baseline requirements. 

This still needs to be done.
> Also, Section 7.1.4.2.2 of the CP (Subject distinguished name fields), or a corresponding provision of the CPS, could be updated and written as more specific to the DV certificates issued by ISRG.

**Comment by bdaehlie** [comment]
We are not planning to remove everything that isn't strictly relevant from our CP.
