### ISSUE TITLE
Move CAA identifying domain info from CPS 4.2.4 to 4.2.1

### ISSUE THREAD

**Issue by aarongable** [letsencrypt/cp-cps#69]
The corresponding language is in CP 4.2.1, so the CPS language should be in the same section.

**Comment by jsha** [comment]
[CPS 3.2.5 Validation of authority](https://letsencrypt.org/documents/isrg-cps-v3.3/#3.2.5-validation-of-authority):
> Organizations have the option to specify CA issuance authority via CAA
> records, which ISRG respects.

[CPS 4.2.1 Performing identification and authentication functions](https://letsencrypt.org/documents/isrg-cps-v3.3/#4.2.1-performing-identification-and-authentication-functions):
> ISRG checks for relevant CAA records prior to issuing certificates. The CA
> acts in accordance with CAA records if present. The CA’s CAA identifying
> domain is ‘letsencrypt.org’.

[CPS 4.2.4 CAA Record Checking](https://letsencrypt.org/documents/isrg-cps-v3.3/#4.2.4-caa-record-checking):
> As part of the issuance process, ISRG will check for CAA records and follow
> the processing instructions found, for each dNSName in the subjectAltName
> extension of the certificate to be issued, as specified in RFC 8659. If the CA
> issues, the CA will do so within the TTL of the CAA record, or 8 hours,
> whichever is greater.
>
> See Section 3.2.2.8 of the ISRG CP for more information about CAA checking
policy.

We should consolidate all of these sections into a single section.

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1701317

> https://bugzilla.mozilla.org/show_bug.cgi?id=1701317
> Needs to be fixed. The Baseline Requirements require that the CCA record processing practices appear in section 4.2 of the CP/CPS. Currently, this language appears in section 3.2.2.8 of the CP, which is good, but this language needs to be relocated to section 4.2.
