### ISSUE TITLE
CPS 4.9: Remove subtext

### ISSUE THREAD

**Issue by andygabby** [letsencrypt/cp-cps#77]
https://github.com/letsencrypt/cp-cps/blob/master/CPS.md#49-certificate-revocation-and-suspension

We can probably remove this line:

`Certificate revocation permanently ends the certificate's operational period prior to its stated validity period.`

**Comment by jsha** [comment]
The reasoning here is that revocation is already well-specified by the various standards documents, and introducing our own summary of revocation runs the risk of unintentionally conflicting meanings.
