### ISSUE TITLE
CP Section 6.1.6 has a small typo

### ISSUE THREAD

**Issue by ezekiel** [letsencrypt/cp-cps#81]
In the final paragraph of Section 6.1.6, the ISRG CP includes text from the BR, but appears to have a typo.

The existing text:
`[Source: Sections 5.6.2.3.2 and 5.6.2.3.3, respectively, of NIST SP 56A: Revision 2]`

The corrected text:
`[Source: Sections 5.6.2.3.2 and 5.6.2.3.3, respectively, of NIST SP 800‐56A: Revision 2]`

**Comment by aarongable** [comment]
Resolved by #111
