### ISSUE TITLE
Add definitions: "CSPRNG", "final certificate"

### ISSUE THREAD

**Issue by ezekiel** [letsencrypt/cp-cps#84]
"CSPRNG" is used in both the CP and CPS without an outset definition. We could adopt BR definition language:

`CSPRNG: A random number generator intended for use in cryptographic system.`

**Comment by jsha** [comment]
We also use the term "final certificate" without defining it. Proposed definition:

"A certificate that contains SCTs and does not contain Precertificate Poison."

**Comment by aarongable** [comment]
Ignoring "final certificate" for now, as it is not a term which appears in the BRs glossary.

**Comment by aarongable** [comment]
Definitions updated by #111
