### ISSUE TITLE
Automate Updates to CP

### ISSUE THREAD

**Issue by aarongable** [letsencrypt/cp-cps#86]
Our CP is deliberately a word-for-word copy of a subset of the Baseline Requirements: those sections which apply to us (most of them), sans those sections which do not (e.g. organization validation).

We should automate this process. For example:
* A template containing placeholders for sections from the BRs, plus our own content (such as our contact info in Section 1)
* A file which lists every section of the BRs/CP, with a boolean indicating whether that section should be copied into our CP
* A process which runs once every 24 hours, looks for changes to the BRs github repo, checks if they are in relevant sections, and creates a PR against this repo

**Comment by bdaehlie** [comment]
I think we're planning to address this by just publishing a combined CP/CPS incorporating the BRs by reference. Is that your view as well @aarongable?
