### ISSUE TITLE
Define "Authorization Domain Name" & use it or "FQDN" instead of "domain"

### ISSUE THREAD

**Issue by jprenken** [letsencrypt/cp-cps#94]
In CP Section 3.2.2.4.7, we use the term "Authorization Domain Name" but haven't defined it in the glossary, which we should do for clarity.

With that being done, it would be much more precise to use "Authorization Domain Name" or "FQDN" (as appropriate, keeping wildcards in mind) instead of "domain" in most cases throughout the CPS, especially in Section 3 (for example, 3.2.2).

**Comment by aarongable** [comment]
The CP portion of this is resolved by #111

**Comment by jprenken** [comment]
There are still some sections where ADN or FQDN might be clearer: 3.1.2, 3.1.3, 3.1.6, 4.9.2
