### ISSUE TITLE
CPS Section 4.9.11: Clarify that stapling is optional

### ISSUE THREAD

**Issue by jprenken** [letsencrypt/cp-cps#97]
CP Section 4.9.11 talks about optionally _requiring_ that subscribers staple OCSP. The corresponding CPS section is correct that we allow stapling, but confusing when compared to the CP's context. It would be nice to clarify this language.

**Comment by aarongable** [comment]
I suggest pairing this with #73, which will require a large enough block of text that I'm not tackling it myself right now.

**Comment by aarongable** [comment]
This has been resolved by #111, which removed the text about stapling from CP 4.9.11 to bring it in line with the BRs.
